//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoEstudio2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioKNEntities : DbContext
    {
        public CasoEstudioKNEntities()
            : base("name=CasoEstudioKNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasasSistema> CasasSistema { get; set; }
    
        public virtual ObjectResult<ConsultarCasas_Result> ConsultarCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCasas_Result>("ConsultarCasas");
        }
    
        public virtual ObjectResult<ConsultarCasasDisponibles_Result> ConsultarCasasDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarCasasDisponibles_Result>("ConsultarCasasDisponibles");
        }
    
        public virtual ObjectResult<Nullable<decimal>> ConsultarPrecioCasaPorId(Nullable<long> pIdCasa)
        {
            var pIdCasaParameter = pIdCasa.HasValue ?
                new ObjectParameter("pIdCasa", pIdCasa) :
                new ObjectParameter("pIdCasa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ConsultarPrecioCasaPorId", pIdCasaParameter);
        }
    
        public virtual int Reserva(Nullable<long> pIdCasa, string pUsuarioAlquiler)
        {
            var pIdCasaParameter = pIdCasa.HasValue ?
                new ObjectParameter("pIdCasa", pIdCasa) :
                new ObjectParameter("pIdCasa", typeof(long));
    
            var pUsuarioAlquilerParameter = pUsuarioAlquiler != null ?
                new ObjectParameter("pUsuarioAlquiler", pUsuarioAlquiler) :
                new ObjectParameter("pUsuarioAlquiler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reserva", pIdCasaParameter, pUsuarioAlquilerParameter);
        }
    }
}
